## `async`

`async function` 用来定义一个返回 [`AsyncFunction`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction) 对象的异步函数。异步函数是指通过事件循环异步执行的函数，它会通过一个隐式的 [`Promise`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise) 返回其结果。如果你在代码中使用了异步函数，就会发现它的语法和结构会更像是标准的同步函数。

### 语法：

一个`async`异步函数可以包含[`await`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/await)指令，该指令会暂停异步函数执行，并等待`Promise`执行，然后继续执行异步函数，并返回结果。

> `await` 关键字只在异步函数内有效。如果你在异步函数外使用它，会抛出语法错误。

注意，当异步函数暂停时，它调用的函数会继续执行(收到异步函数返回的隐式 `Promise`)

```
async function name([param[, param[, ... param]]]) { statements }
```

- `name`：函数名称。

- `param`：要传递给函数的参数。

- `statements`：函数体语句。

**返回值：**

`async function` 的返回值将被隐式地传递给 `Promise.resolve`，换句话说它会根据 `renturn` 的值作为`[[PromiseValue]]`封装一个`Promise`并返回，如果执行过程中出错就会返回一个状态为`reject`的`Promise`。

> `async`/`await`的目的是简化使用多个 `promise` 时的同步行为，并对一组 `Promises`执行某些操作。正如`Promises`类似于结构化回调，`async`/`await`更像结合了`generators`和` promises`。

### 被忽略的错误

但是，`async`函数仍有可能然可能错误地忽略错误，以下面的异步函数为例。 如果它没有等待`await Promise.all([])`调用的结果，则不会传播任何错误。

```js
async function parall() {Promise.all([Promise.reject(1)])
```

**原理和解决：**

`Await`并不会改变`async`的返回值，不过也可能发生一些特殊情况，首先要知道`Promise.reject(1)`不处理的话会抛出一个异常（函数执行过程中会抛出一个错误等待处理）。

```js
Promise.reject(1)
// Uncaught (in promise) 1
// Promise {<rejected>: 1}
// [[PromiseStatus]]: "rejected"
// [[PromiseValue]]: 1
```

正常情况下`async`中抛出错误是会改变返回状态，但是因为这里的执行是异步的，所以不会改变状态。

```js
async function a(){Promise.reject(1)}; a();
// Promise {<resolved>: undefined)
// 一样的原理
async function a(){setTimeout(()=>{throw 1})}; a();
// Promise {<resolved>: undefined}
```

但是我们要是使用`await`进行等待就不一样了，`await`会等待`Promise`的执行并且将`promise`的`reject`状态抛出，不过要记住`await`本身不会改变`async`的返回。

```js
async function a(){await Promise.reject(1)}; a();
// Promise {<rejected>: 1}
```

### 改写`Promise`链

返回 [`Promise`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)的 API 将会产生一个` promise` 链，它将函数肢解成许多部分。例如下面的代码：

```js
function getProcessedData(url) {
  return downloadData(url) // 返回一个 promise 对象
    .catch(e => {
      return downloadFallbackData(url)  // 返回一个 promise 对象
    })
    .then(v => {
      return processDataInWorker(v); // 返回一个 promise 对象
    });
}
```

可以重写为单个`async`函数：

```js
async function getProcessedData(url) {
  let v;
  try {
    v = await downloadData(url); 
  } catch (e) {
    v = await downloadFallbackData(url);
  }
  return processDataInWorker(v);
}
```

## `await`

`await` 操作符类似求值表达式，用于等待一个[`Promise`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise) 对象。**它只能在异步函数 [`async function`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/async_function) 中使用**，`await`还能获取到`[[PromiseValue]]`的值作为表达式的值，这实现了对异步的精确控制。

**Promise实例的结构：**

```js
Promise {<pending>}
	__proto__: Promise
    catch: ƒ catch()
    constructor: ƒ Promise()
    finally: ƒ finally()
    then: ƒ then()
  [[PromiseStatus]]: "resolved"
  [[PromiseValue]]: 1
```

### 语法：

`await` 表达式会暂停当前 [`async function`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/async_function) 的执行，等待 `Promise` 处理完成。

若 `Promise` 正常处理`(fulfilled)`，其回调的`resolve`函数参数`（PromiseValue）`作为 `await` 表达式的值，继续执行 [`async function`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/async_function)。

若 `Promise` 处理异常`(rejected)`，`await` 表达式会把 `Promise` 的**异常原因抛出**，如果` await` 操作符后的表达式的值不是一个 `Promise`，则返回该值本身。

```
[return_value] = await expression;
```

- **expression：**

  一个 [`Promise`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise) 对象或者任何要等待的值。

- **return：**

  返回 `Promise` 对象的处理结果。**如果等待的不是 `Promise` 对象，则返回该值本身**。

### 例子：

如果一个` Promise `被传递给一个` await `操作符，`await `将等待 `Promise` 正常处理完成并返回其处理结果。

```js
function resolveAfter2Seconds(x) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(x);
    }, 2000);
  });
}

async function f1() {
  var x = await resolveAfter2Seconds(10);
  console.log(x); // 10
}
f1();
```

如果该值不是一个` Promise`，`await `会把该值转换为已正常处理的`Promise`，然后等待其处理结果。

```js
async function f2() {
  var y = await 20;
  console.log(y); // 20
}
f2();
```

如果` Promise `处理异常，则异常值被抛出。

```js
async function f3() {
  try {
    var z = await Promise.reject(30);
  } catch (e) {
    console.log(e); // 30
  }
}
f3();
```

